# Generated by Django 6.0.6 on 2026-06-16 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Guia',
            new_name='GuiaDeMuseo',
        ),
    ]
