# Generated by Django 6.0.6 on 2026-06-16 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museos', '0002_rename_guia_guiademuseo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibicion',
            name='costo_produccion',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='costo_produccion'),
        ),
        migrations.AlterField(
            model_name='exhibicion',
            name='duracion_meses',
            field=models.IntegerField(verbose_name='duracion_meses'),
        ),
        migrations.AlterField(
            model_name='exhibicion',
            name='guia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exhibiciones', to='museos.guiademuseo', verbose_name='guia'),
        ),
        migrations.AlterField(
            model_name='exhibicion',
            name='tematica',
            field=models.CharField(max_length=200, verbose_name='tematica'),
        ),
        migrations.AlterField(
            model_name='exhibicion',
            name='titulo_exhibicion',
            field=models.CharField(max_length=250, verbose_name='titulo_exhibicion'),
        ),
        migrations.AlterField(
            model_name='guiademuseo',
            name='años_experiencia_guia',
            field=models.IntegerField(verbose_name='años_experiencia_guia'),
        ),
        migrations.AlterField(
            model_name='guiademuseo',
            name='idiomas_hablados',
            field=models.CharField(max_length=300, verbose_name='idiomas_hablados'),
        ),
        migrations.AlterField(
            model_name='guiademuseo',
            name='museo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guias', to='museos.museo', verbose_name='museo'),
        ),
        migrations.AlterField(
            model_name='guiademuseo',
            name='nombre_completo',
            field=models.CharField(max_length=200, verbose_name='nombre_completo'),
        ),
        migrations.AlterField(
            model_name='museo',
            name='año_fundacion',
            field=models.IntegerField(verbose_name='año_fundacion'),
        ),
        migrations.AlterField(
            model_name='museo',
            name='ciudad',
            field=models.CharField(max_length=150, verbose_name='ciudad'),
        ),
        migrations.AlterField(
            model_name='museo',
            name='nombre',
            field=models.CharField(max_length=150, unique=True, verbose_name='nombre'),
        ),
    ]
